apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 3000
    - name: "443"
      port: 443
      targetPort: 3443
  type: LoadBalancer
  selector:
    io.kompose.service: app
