services:
 postgres:
  image: postgres
  restart: always
  container_name: postgres
  hostname: postgres
  ports:
   - 5432:5432
  environment:
   - POSTGRES_USER=ox
   - POSTGRES_DB=api
   - POSTGRES_PASSWORD=ox
  volumes:
   - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql

 app:
  image: aaronhmiller/crud-app
  restart: unless-stopped
  container_name: crud-app
  hostname: crud-app
  depends_on:
   - postgres
  ports:
   - 80:3000
   - 443:3443
  environment:
   - KEY=${KEY}
   - CERT=${CERT}
  healthcheck:
   test: wget --quiet --output-document=- http://localhost:3000/healthcheck || exit 1
   interval: 3s
   timeout: 3s
   retries: 3
   start_period: 5s
