FROM cgr.dev/ay-ay-ron.dev/node:latest
USER root
WORKDIR /app
COPY package.json .
RUN npm install
COPY . ./
RUN adduser -D myuser && \
    chown -R myuser:myuser /app
USER myuser
EXPOSE 3000 3443
HEALTHCHECK --interval=30s --timeout=5s CMD wget -qO- http://localhost:3000/healthcheck || exit 1
CMD ["app.js"]
