pipeline:
  identifier: Build_aaronhmiller_crud_app_1737771321330
  name: Build crud-app
  orgIdentifier: default
  projectIdentifier: test2
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: aaronhmiller/crud-app
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: false
            paths: []
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          buildIntelligence:
            enabled: false
        type: CI
        description: ""
    - stage:
        name: check stage
        identifier: check_stage
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: review
                  identifier: review
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
