pipeline:
  identifier: Build_aaronhmiller_crud_app_1737771321330
  name: Build crud-app
  orgIdentifier: default
  projectIdentifier: test2
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: aaronhmiller/crud-app
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
