name: Branch Docker Hub CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3.6.0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2.2.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.10.0
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Branch build and push
        uses: docker/build-push-action@v3.3.1
        with:
          file: ./app/Dockerfile
          context: ./app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
          platforms: linux/amd64,linux/arm64

