name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    # set at job level
    env:
      GITHUB_REPOSITORY_ID: ${{ github.repository_id }}
      OX_API_KEY: ${{ secrets.OX_API_KEY }}

    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
    - name: Run the app
      run: docker-compose up -d
    - name: Test app
      run: |
        NAME=$(docker run --network crud-app_default saltaaron/just-httpie GET crud-app:3000/users/1 | docker run -i --network crud-app_default saltaaron/just-jq -r '.[].name')
        if [ $NAME != 'Marcia' ] ; then
          echo "The expected name was not returned. $NAME was returned instead."
          exit 1;
        fi
    - name: Test TLS
      run: |
        NAME=$(docker run --network crud-app_default saltaaron/just-httpie GET https://crud-app:3443/users/2 --verify no | docker run -i --network crud-app_default saltaaron/just-jq -r '.[].name')
        if [ $NAME != 'Amy' ] ; then
          echo "The expected name was not returned. $NAME was returned instead."
          exit 1;
        fi

    - name: Run CUSTOMIZED OX Security Scan to check for vulnerabilities
#    - name: Run OX Security Scan to check for vulnerabilities
#      with:
#        ox_api_key: ${{ secrets.OX_API_KEY }}
#        ox_timeout: 1
#        ox_fail_on_timeout: true
      run: |
        ${{ github.workspace }}/.github/workflows/custom-ox.sh
#      uses: oxsecurity/ox-security-scan@main

