name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches: [main]
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.6.0
      - name: Update diagram
        uses: githubocto/repo-visualizer@0.9.1
        with:
          excluded_paths: "diagram.svg,app/.dockerignore,.github,.gitignore,LICENSE"
          branch: diagram
