name: Tagged Docker Hub CI

on:
#  push:
#    tags: [ "v*" ]
  create:
    tags: [ "v*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4.6.0@818d4b7b91585d195f67373fd9cb0332e31a7175
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=auto
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.10.0@885d1462b80bc1c1c7f0b00334ad271f09369c55
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2.2.0@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Tagged build and push
        uses: docker/build-push-action@v3.3.1@1104d471370f9806843c095c1db02b5a90c5f8b6
        with:
          file: ./app/Dockerfile
          context: ./app
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
